name: "Apple Maintained Bot Workflow"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15

    - name: checkout
      uses: actions/checkout@v2

    - name: lint
      run: |
        GO111MODULE=off GOBIN=$(pwd)/bin go get golang.org/x/lint/golint
        bin/golint -set_exit_status ./...

    - name: test
      run: go test -coverprofile=profile.csv ./...

    - name: send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.csv
        flag-name: Go-1.15
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true

  release-heroku:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Release to heroku
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: deploy to heroku
      uses: akhileshns/heroku-deploy@v3.5.7
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: apple-maintained-bot
        heroku_email: rikeda71@gmail.com
        usedocker: true